### ISSUE TITLE
Not being able to sync the dependeinces

### ISSUE THREAD

**Issue by codeaskush** [prabhat1707/DbExporterHelper#2]
null |  
-- | --
D:/Android/Project/NewDB |  
app/build.gradle |  
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.prabhat1707:DbExporterHelper:v1.0. Open FileShow Details |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.prabhat1707:DbExporterHelper:v1.0. Open FileShow Details |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.prabhat1707:DbExporterHelper:v1.0. Open FileShow Details |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.prabhat1707:DbExporterHelper:v1.0. Open FileShow Details |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.prabhat1707:DbExporterHelper:v1.0. Open FileShow Details |

**Comment by prabhat1707** [comment]
thanks @schixor88 for you feedback, I will check it.

**Comment by prabhat1707** [comment]
it’s working @schixor88 send me your build screenshot if it not.
